### ISSUE TITLE
Add support for defining file output

### ISSUE THREAD

**Issue by scyt** [jtheoof/swappy#1]
I prefer to store screenshots in a specific directory that isn't $XDG_CONFIG_HOME/Desktop. Can you add support for specifying an output dir and filename on save?

Related, can the output be sent back to stdout so I can send it to something like pngquant? My current workflow involves sending from grim to pngquant, and I'd like to insert swappy in between so I can annotate the screenshots before sending them back to stdout.

**Comment by Biont** [comment]
Same here. I was immediately greeted with a `** (process:88547): CRITICAL **: 20:53:32.916: could not find a valid pictures path in your env variables` when I tested it out, hoping I could just throw this into my screengrabbing pipe chain for easy and effortless on-the-fly editing - something I've been searching for quite a while. This would be a very welcome addition.

**Comment by jtheoof** [comment]
Thanks for the feedback guys, I'll separate this issue into two:

- Have some basic configs like the output dir and the font configurable in the same vein as:  [mako](https://github.com/emersion/mako/blob/master/mako.1.scd#L199)
- Add ability to output the final swappy surface to stdout for more piping love.

I'll get to it over the weekend.

**Comment by jtheoof** [comment]
It's done for the configuration part, I'll tackle the more interesting part for you guys next week. See #2

**Comment by jtheoof** [comment]
@Biont @scyt :tada: check out option `-o -` in the man / readme. Happy piping.

**Comment by Biont** [comment]
Thanks @jtheoof ! Works nicely on a first test. This is amazing!
