### ISSUE TITLE
Can this be used to redact data?

### ISSUE THREAD

**Issue by 3lpsy** [jtheoof/swappy#109]
When saving & generating the new image, are painted over areas completely lost? I don't plan on using this for work or anything with a lot at stake. But if I wanted to maintain some anonymity when sharing things like screenshots, could the original portions of the image that were painted over be recovered? Thanks.

**Comment by jtheoof** [comment]
@3lpsy As long as you don't exit swappy, you can still undo or reset your change. However the final pixbuf saved will always be based on your drawings. It's the nature of the tool.
