### ISSUE TITLE
Missing dependencies in REAMDE

### ISSUE THREAD

**Issue by matthiasbeyer** [jtheoof/swappy#11]
Hi!

It seems that the following dependencies are not listed in the README:

* ninja
* pkgconfig 
* cmake
*  scdoc
*  gio-sharp
* libnotify

Maybe you wanna update that file.

(Context: I'm packaging this for nixos).

**Comment by jtheoof** [comment]
Those are `dev` dependencies. Some of them are not mandatory. `libnotify`. And `gio-sharp` does not exist in Arch.

**Comment by jtheoof** [comment]
@matthiasbeyer why `cmake`? Also `libnotify` is listed in the optional depedencies of the README.

**Comment by maximbaz** [comment]
@jtheoof by the way, have you considered cutting releases, in order to package non-git version of the app?

**Comment by jtheoof** [comment]
There isn't enough development to justify a release cycle. Perhaps at some point if there is more activity.
