### ISSUE TITLE
Swappy doesn't show window manager borders

### ISSUE THREAD

**Issue by lokesh-krishna** [jtheoof/swappy#111]
Is it intentional that swappy doesn't show borders as set in my window manager's (sway) settings? I am using a custom GTK theme which has the same background as my terminal and when taking screenshots with the terminal open, swappy's background just completely merges with the terminal. 

Is there a way to manually enable borders for swappy?

**Comment by f1nniboy** [comment]
You can add `for_window [app_id="swappy"] border pixel 1` to your sway configuration. Change the number to your wanted border width.

**Comment by lokesh-krishna** [comment]
Thanks a lot, that works perfectly!
