### ISSUE TITLE
Not able to resize window at all on Sway

### ISSUE THREAD

**Issue by rieje** [jtheoof/swappy#113]
I'm not able to resize window at all on Sway, either via keybindings on the focused window or with dragging the corners. This is the first time I've ever experienced an app on Wayland with this behavior--very strange.

--------------------

Also, when running `swappy` without any arguments on the terminal, I get:

    ** (swappy:2970663): CRITICAL **: 02:23:31.636: original image not loaded

    (swappy:2970663): GLib-GObject-CRITICAL **: 02:23:31.640: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

I had assumed  swappy wouldn't work at all. I would expect it to open a window and allow the option to select an image file. Not sure if this is a bug.

**Comment by jtheoof** [comment]
@rieje Both points mentionned are "by design".

Swappy current `GtkApplicationWindow` has property `resizable` set to `false`. The main purpose is to have an overlay on top of the current windows for quick annotations.

Swappy also requires an image to be passed through command line (`stdin` or using `-f`). So the error message is expected. Swappy is not gimp.

**Comment by rieje** [comment]
Wouldn't it be better to allow the user to customize the window? I don't see any advantages having a fixed window size. Or at least a default size on launch that can still be customized. Right now I'm trying to edit a phone pic of a restaurant menu but the window is small and the text on the picture is difficult to read/annotate unless it can be blown up. 

Also, swappy opens the picture upside down. On 2 image viewers, it opens the picture correct side up. Might be a bug? There's seems to be no option to rotate the picture on swappy.

**Comment by jtheoof** [comment]
See #57 for the resize request.
