### ISSUE TITLE
Publish PGP key

### ISSUE THREAD

**Issue by maximbaz** [jtheoof/swappy#116]
Hi there 👋 

Quick request, could you please publish your PGP key to https://keys.openpgp.org/ and perhaps also https://keyserver.ubuntu.com/ ?

As the old SKS pool is no longer in use, your key is currently only available on Github :)

Thanks!

**Comment by jtheoof** [comment]
Hi @maximbaz it's done but it didn't push my user id, not sure if that's normal:

```
❯ gpg --keyserver hkps://keys.openpgp.org/ --search-keys 6A6B35DBE9442683
gpg: data source: https://keys.openpgp.org:443
(1)	  4096 bit RSA key 6A6B35DBE9442683, created: 2020-06-19
Keys 1-1 of 1 for "6A6B35DBE9442683".  Enter number(s), N)ext, or Q)uit > 1
gpg: key 6A6B35DBE9442683: no user ID
gpg: Total number processed: 1
```

I pushed it via:

```
❯ gpg --keyserver hkps://keys.openpgp.org/ --send-keys 6A6B35DBE9442683
gpg: sending key 6A6B35DBE9442683 to hkps://keys.openpgp.org/
```

**Comment by jtheoof** [comment]
Never mind, it required a contact email verification. Should be good now.

**Comment by maximbaz** [comment]
Thanks!
