### ISSUE TITLE
Add examples to man page or --help output

### ISSUE THREAD

**Issue by Jaakkonen** [jtheoof/swappy#118]
The `grim` `-` argument is easy to forget and swappy just silently fails and it's easy to run `swappy -` where you mean `swappy -f -`. The working examples are in README.md but I think it would be nice to have those in man page examples section or even in the `swappy --help` output.

**Comment by jtheoof** [comment]
I really don't think that the man page is the place to document non-dependency of tools (like `grim` or `slurp`). Swappy can be used outside of the sway ecosystem.
