### ISSUE TITLE
[Request] Option to set default state of paint panel & tool

### ISSUE THREAD

**Issue by Biont** [jtheoof/swappy#12]
Hello again!

This tool keeps putting a smile on my face every workday and I would like to thank you again for creating it.

My main use case is highlighting specific parts of a screenshot - because I'd use grim/slurp directly if it wasn't. Therefore, I almost always need to bring up the paint panel (then select rectangle/arrow because I don't want to annoy people with shitty mouse drawings). It would be pretty cool if I could force-enable the paint panel in the config file - and probably even the default tool selection.

What do you think about adding such a feature?

**Comment by jtheoof** [comment]
That's a fair request @Biont. Have you considered also the keyboard shortcuts in the meantime? `A` for arrow, `R` for rectangle, ... I never toggle the panel unless I need to play with the color of the drawing.

**Comment by Biont** [comment]
Sure I use them and I admit that I am asking for something rather trivial which probably only adds up to a slight inconvenience during a regular work day.  
It's still a feature that pops up in my head whenever I have to go bring up my desired panel. I cannot tell how much hassle it would be to implement this though, so I will absolutely be happy with whatever you decide

**Comment by jtheoof** [comment]
I was thinking. How about a `persist_state` option? That way you find swappy UI in the same state you were in last time. Would that work better or you'd still prefer a default tool selection? I'm just thinking of ideas.

**Comment by Biont** [comment]
I believe that would work reasonably well. Another option would be command line arguments/flags to launch swappy in the desired state.

**Comment by jtheoof** [comment]
Hi @Biont so I've added a `show_panel` setting in the `config` file. 

With this part in your `~/.config/swappy/config`:
```
[Default]
...
show_panel=true
...
```

You'll be able to have the panel on when starting swappy.

Regarding the mode as CLI input params, I'm not convinced yet. This is mainly a UI tool, if I add more painting modes, it will become a little harder to maintain.

I'll wait to see if more users ask for this feature.

**Comment by Biont** [comment]
Awesome, thank you so much
