### ISSUE TITLE
bug: original image not loaded

### ISSUE THREAD

**Issue by mizzunet** [jtheoof/swappy#128]
Swappy fails to open with output,
```

~/Pictures 
󰅂 swappy download.jpeg 

** (swappy:784): CRITICAL **: 15:31:18.381: original image not loaded
```

It's just been started happening recently. 

I tried after removing config, still fails, so it's not that.

Swappy version: 1.4.0-1

OS: Artix

**Comment by jtheoof** [comment]
Use the `-f` option.
