### ISSUE TITLE
Cannot install from AUR: "Signature is marginal trust"

### ISSUE THREAD

**Issue by hakanyi** [jtheoof/swappy#132]
Attempting to install via `yay` results in:
```
error: swappy: signature from "Maxim Baz <pgp@maximbaz.com>" is marginal trust
:: File /var/cache/pacman/pkg/swappy-1.4.0-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
```
Using latest version of Manjaro Sway.

**Comment by jtheoof** [comment]
Thanks for reporting this. I've contacted Maxim Baz. In the meantime, perhaps you can install `yay -S swappy-git`.

**Comment by maximbaz** [comment]
Hi there, thanks for the ping, this issue has been [fixed on 17-07-2022](https://archlinux.org/todo/rebuild-packages-signed-by-old-marginally-trusted-packager-keys/), but unfortunately Manjaro is slow at backporting our fixes.  Another alternative to the suggested one is to install swappy from Arch repos directly, e.g. via 

```
sudo pacman -U https://archlinux.org/packages/community/x86_64/swappy/download
```

**Comment by jtheoof** [comment]
Thanks @maximbaz. I've pinged [the manjaro devs](https://forum.manjaro.org/t/update-requests-for-packages-imported-from-arch-linux/493/280?u=jtheoof). Will close this issue as it's not really swappy related. Thanks for the heads up @hakanyi.
