### ISSUE TITLE
"original image not loaded" when piping image in via stdin

### ISSUE THREAD

**Issue by jazzpi** [jtheoof/swappy#137]
Piping the output of `grim` (or of `cat image.png`) into swappy causes it to fail with

> ** (swappy:18194): CRITICAL **: 15:39:17.249: original image not loaded

`swappy -f image.png` works fine.

I'm on Fedora 36, using Sway version 1.7 and swappy version 1.4.0.

**Comment by jtheoof** [comment]
Can you post the command you use?

**Comment by jazzpi** [comment]
I was using `cat image.png | swappy`. After rereading the manpage, I realized I should use `cat image.png | swappy -f -`, which works fine. Sorry for any confusion.
