### ISSUE TITLE
[request] Blur tool

### ISSUE THREAD

**Issue by cyrinux** [jtheoof/swappy#17]
Hi,

First thanks for this cool project !

Cool you please add the basic blur tool in swappy?

Best regards

**Comment by jtheoof** [comment]
Thanks for the feedback @cyrinux . Snappy on macOS does not have a blur tool. Could you describe a little more what you'd want?

**Comment by cyrinux** [comment]
Hi @jtheoof , I use before ksnip https://github.com/ksnip/ksnip you can see on this page a presentation of some tool.
Bluring tool is to hide a sensible information for example you see?
Ksnip was really good but too many deps from kde for example.
Tell me if you see more information.
![image](https://user-images.githubusercontent.com/519083/83110720-cd339c80-a0c3-11ea-9733-b1f386827f45.png)

**Comment by jtheoof** [comment]
Thanks @cyrinux I'll see how I can do that with cairo

**Comment by jtheoof** [comment]
@cyrinux I hacked around blur and cairo over the weekend. It's not perfect, cursor and performance need some more love. But should do the trick if you don't abuse blurring.

![image](https://user-images.githubusercontent.com/90020/83373373-14f14700-a396-11ea-8552-14a3ad4ec5c7.png)

Let me know what you think.

**Comment by cyrinux** [comment]
Hi @jtheoof , thanks !
That make the jobe 🥳 , I hope you appreciate my entertainment suggestion 🤣 .

After I can suggest to make it even better:
* Add possibility to draw a bluring rectangle, to be able to quick and neat blur a text zone for example.(this will maybe help for my second point above)
* About performance, on laptop with my trackpad, sometimes I feel my finger move is smooth but this create no-blurred hole all on my way, I understand this depend on the speed, don't know what you can do for this.
* The drop water icon need maybe gray polishing as other tools? 
![image](https://user-images.githubusercontent.com/519083/83382943-70e2bc80-a3e4-11ea-9b64-c0caf16caf37.png)

Thanks you very much is already functional ;) 💯

**Comment by maximbaz** [comment]
Thank you very much @jtheoof! I'll add just a couple of points from my side too:

1. I agree that a blur rectangle would be a better implementation than a blur brush, more often one needs to hide sensitive area of the screenshot, let that be some text or a picture, and it's much much faster to draw a rectangle, inside which everything must get blurred. Maybe this will even be more efficient performance-wise, if you know the rectangle in advance, instead of following the cursor?

1. The math on scaled displays seems to be currently off, I have `2.5` scale, and when I drag a mouse cursor with blur tool, the blurring happens in a different place of the screenshot, not where my mouse cursor is 🙂

**Comment by jtheoof** [comment]
Thanks for the feedback guys, I'll reopen the issue and work on improving the blurring in future work.

**Comment by jtheoof** [comment]
I've add a more natural rectangle-ish aspect to the blur. @cyrinux @maximbaz if you give it a try and le me know :) I removed the blur as brush aspect. 

I created #20 to track performance issues.

**Comment by maximbaz** [comment]
Thank you very much @jtheoof! I can tell you that the "usage experience" is just perfect now, rectangle is truly what we needed. It works well on my scaled display as well now 👍 

If you are still not sick of us and seeking for further improvement ideas (😄), one thing I would change is "strength" of the blur. Here's an example of me applying blur N times to try to hide the text, I would argue that even after 5 times the blurred text can be recognized.

![image](https://user-images.githubusercontent.com/1177900/83500143-abb92300-a4be-11ea-811c-c3257e2e29fe.png)

I have two ideas: either simply play with constants to make the blur a lot more aggressive, or replace blur with pixelate algorithm? A random example of what it might look like: 

![image](https://user-images.githubusercontent.com/1177900/83500423-09e60600-a4bf-11ea-8eb2-113dfdb628c6.png)

**Comment by cyrinux** [comment]
Hi, thanks @jtheoof  ,
I want to do the same remark as @maximbaz about the strengh of the blur.
Other things are good !

**Comment by maximbaz** [comment]
I just saw that blur level is actually configurable, with `500` being the max value. I would argue that even that is not enough, and blurring 5 times with level 500 is still quite "readable" (especially if you can guess the pattern of the text being hidden), but 10 times 500 level is what I would already consider enough for hiding a sensitive content 🙂 

![image](https://user-images.githubusercontent.com/1177900/83578442-13ab5000-a537-11ea-9986-5b60a7f74146.png)

**Comment by jtheoof** [comment]
OK thanks I'll play around to provide more effective blur.

**Comment by jtheoof** [comment]
See #22

**Comment by jtheoof** [comment]
@cyrinux  @maximbaz With #25 I've done some improvements with bluring algo and rendering. Should now be much smoother and scale well on High DPI displays. Let me know what you think.

**Comment by cyrinux** [comment]
Hi @jtheoof cool yes its smoother for me, and icon is better :-)

**Comment by maximbaz** [comment]
I agree @jtheoof, it is amazing now, thank you once again for your improvements!
