### ISSUE TITLE
Link to AUR doesnt work

### ISSUE THREAD

**Issue by inson1** [jtheoof/swappy#170]
https://archlinux.org/packages/community/x86_64/swappy/

**Comment by eightballocto** [comment]
If you're looking for the main "stable" release, you can find it here:
https://archlinux.org/packages/extra/x86_64/swappy/

it was moved to the "Extra" repos, apparently. No need to get it from the AUR.

If you want the "git" version, you can find it here and install it yourself or with an AUR helper:
https://aur.archlinux.org/packages/swappy-git
