### ISSUE TITLE
unable to load file: /tmp/swappy-stdin-WCN1M2.png

### ISSUE THREAD

**Issue by cosme-benito** [jtheoof/swappy#174]
When running the command `grim -g "$(slurp)" - | swappy -f -` I get the error:

```
unable to load file: /tmp/swappy-stdin-WCN1M2.png - reason: Couldn’t recognize the image file format for file “/tmp/swappy-stdin-WCN1M2.png”
```
I thought it was some permission error or something so  I created the file `$HOME/.config/swappy.config` with the contents:

```
[Default]
save_dir=$HOME/Pictures/screenshots
save_filename_format=swappy-%Y%m%d-%H%M%S.png
show_panel=true
line_size=5
text_size=20
text_font=sans-serif
paint_mode=brush
early_exit=false
fill_shape=false
```
Unfortunately this does not solve the problem, the configuration is likely being ignored. This used to work, maybe some dependency is broken/missing? 

- I installed swappy from the arch repos, currently on version 1.5.1-1
- Installing the `swappy-git` from the AUR produces the same error
- `wl-clipboard`, `otf-font-awesome` and `wayland-protocols` are installed

**Comment by tkna91** [comment]
If you write it this way, it looks fine.

```
file=$HOME/Pictures/screenshots/swappy-$(date +%Y%m%d-%H%M%S).png
grim -g "$(slurp)" - | swappy -f - -o $file
```

**Comment by cosme-benito** [comment]
Turns out the problem was completely unrelated to swappy. My `$XDG_DATA_DIRS` was broken and unsetting it solved the problem.
