### ISSUE TITLE
Copy Surface with early_exit -> empty clipboard?

### ISSUE THREAD

**Issue by dagbdagb** [jtheoof/swappy#180]
Noticed this oddity.

If I have early_exit=true in my config, Copy Surface will terminate the program. As expected.
But clipboard appears empty. Disabling early_exit ensures that I can paste from clipboard again.

wayland-protocols-1.36
wayland-1.23.0

**Comment by kadamski** [comment]
I guess you hit the limitation described in the [README](https://github.com/jtheoof/swappy/blob/master/README.md#limitations). Can you try install wl-clipboard and check if this fixes your problem?

**Comment by dagbdagb** [comment]
Bingo!  Thank you very much.
