### ISSUE TITLE
[missing icons] from the sidebar

### ISSUE THREAD

**Issue by cinghiopinghio** [jtheoof/swappy#23]
Great little app. Thanks

In my system(`archlinux` btw) there seems to lack the icons on the buttons on the side panel.

![Swappshot Thu Jun  4 17:40:30 2020](https://user-images.githubusercontent.com/1894436/83778628-3fd7e580-a68b-11ea-9200-90b847b05385.png)

**Comment by jtheoof** [comment]
It seems your interface GTK font doesn't include the UTF-8 emojis required for the buttons labels here. You could override those with a proper CSS config in your `gtk.css` config file.

**Comment by cinghiopinghio** [comment]
I don't understand what I should do. I tried different languages without success.
Can you be more explicit? Thanks

**Comment by jtheoof** [comment]
You simply need to use a font that supports those UTF-8 unicode characters. 
![image](https://user-images.githubusercontent.com/90020/84577634-0f2f3480-ad8c-11ea-99b2-15fc6166ade3.png)

**Comment by jtheoof** [comment]
I'm gonna try to see if I can embed some real world icons so that swappy doesn't rely on your font for rendering those icons.

**Comment by jtheoof** [comment]
@cinghiopinghio You simply need to install `otf-font-awesome`, the `style.css` relies on those font icons to properly draw the icons. I forgot about it.

```
sudo pacman -S otf-font-awesome
```

I'll update the README

**Comment by jtheoof** [comment]
README updated and PKGBUILD updated.
