### ISSUE TITLE
[feature request]: Register mime types to open images with swappy

### ISSUE THREAD

**Issue by nwg-piotr** [jtheoof/swappy#35]
In addition to opening a file with `swappy -f "~/Desktop/my-gnome-saved-file.png"`, which is great, you could also create a `/usr/share/applications/swappy.desktop` entry, and register opening png / jpg files, e.g. like this:

```
MimeType=image/jpeg;image/jpg;image/png;
```

**Comment by jtheoof** [comment]
So I added a desktop file with #41. If you're on Arch, can you install the latest from `swappy-git` and let me know if this is what you expected?

**Comment by nwg-piotr** [comment]
It works perfectly well. It would be even better if it also could open jpg one day. :)

![swappy-scrot](https://user-images.githubusercontent.com/20579136/85633524-b019cb80-b679-11ea-82e9-e9fe422d601d.png)
