### ISSUE TITLE
Text tool does not support UTF-8 properly

### ISSUE THREAD

**Issue by MaxVerevkin** [jtheoof/swappy#43]
Currently, swappy supports only ASCII. Unicode input (tested on ru layout) looks like that:
![image](https://user-images.githubusercontent.com/34583604/85786112-9daf9880-b732-11ea-98df-d2f5bf6842cc.png)

**Comment by jtheoof** [comment]
Just to confirm, you mean using the Text painting tool right?

**Comment by MaxVerevkin** [comment]
@jtheoof Yes

**Comment by MaxVerevkin** [comment]
Still does not work.

**Comment by jtheoof** [comment]
Hello @MaxVerevkin, do you mind trying out the latest `swappy-git` (if you're on Arch)? It should now work for regular UTF-8 keys on your keyboard. The compose key won't work (not sure how to handle that porperly with GTK events), but at least it should be a much more pleasant experience for non ASCII keyboards :)

**Comment by MaxVerevkin** [comment]
@jtheoof Yes, now it works! Thanks :)
