### ISSUE TITLE
"Cairo status: out of memory" error when reading from stdin under PowerShell Core

### ISSUE THREAD

**Issue by Isti115** [jtheoof/swappy#51]
When I try to use swappy with input through stdin (e.g. the output of grim or simply just `cat`-ing a png file) under PowerShell Core (my default shell), I get the following error:
```
** (swappy:9317): WARNING **: 12:59:14.433: error while loading png file: /tmp/swappy-stdin-O1S1N0.png - cairo status: out of memory
```

The same works perfectly with bash. Does anyone have any idea as to what could be causing this issue, or how it could be fixed? My only faint guess is that it might have to do with the fact, that `pwsh` does not have the `<` operator for file to stdin redirection, but piping usually works just the same.

(In the meantime as a workaround I can set up my hotkeys to run through bash, but ideally this extra step shouldn't be needed.)

**Comment by jtheoof** [comment]
Hi @Isti115, are you running swappy under [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or using `pwsh` under Linux? Could you provide a little more info on your environment so that I can try to reproduce this issue?

**Comment by Isti115** [comment]
It's running under a regular Arch install, the default shell is set to
PowerShell Core 7.0.2.

**Comment by jtheoof** [comment]
What is the command that you are trying to run?

**Comment by Isti115** [comment]
The first command I tried was the one suggested by the documentation:
`grim -g "$(slurp)" - | swappy -f -`
and the second one was for editing an existing image, just to see if `grim` or `slurp` might have to do anything with the issue:
`cat 'example-image.png' | swappy -f -`
Both of these work fine under `bash`, but fail under `pwsh`.

**Comment by jtheoof** [comment]
I did a quick investigation @lsti115, and it really seems to be a bug with powershell.

```
PS /home/jtheoof/dev/jtheoof/swappy/docs/images> cat screenshot-1.0.0.png > out.png
PS /home/jtheoof/dev/jtheoof/swappy/docs/images> diff screenshot-1.0.0.png out.png
Binary files screenshot-1.0.0.png and out.png differ
```

I suggest to bring this to the attention of the powershell developers.

**Comment by Isti115** [comment]
Thanks for finding the cause of this issue, I have forwarded it to the PowerShell Core repository.
