### ISSUE TITLE
When editing a textbox and pressing save, the bounding box and cursor are rendered as well

### ISSUE THREAD

**Issue by gabm** [jtheoof/swappy#52]
Expected: We exit the editing mode and then save the image with the text as typed so far
Actual: The bounding box and cursor appear on the saved image

I attached an image to illustrate

![Swappshot Thu Jul 23 13:39:55 2020](https://user-images.githubusercontent.com/482105/88282629-37467780-ccea-11ea-94f5-40a87484f46d.png)

**Comment by apiraino** [comment]
The issue here is that when clicking Save, whatever is on the screenshot "container" will be captured.

As a workaround, one can press ESC before clicking the save button. The text box will disappear and will not be saved.

**Comment by apiraino** [comment]
thanks @jtheoof !
