### ISSUE TITLE
[Feature Request] Add config option for default saved image name format.

### ISSUE THREAD

**Issue by FjorgeTheHuman** [jtheoof/swappy#61]
The current name format is nice, but I would love to be able to change it through the config file.
Thanks!

**Comment by jtheoof** [comment]
My hopes are on @apiraino on this one.

**Comment by apiraino** [comment]
Fixed in #64

**Comment by eoli3n** [comment]
Even better, could you add a text input in the editor panel to manually/optionnaly set the filename ?

**Comment by jtheoof** [comment]
The core of the feature was fixed by @apiraino  in #64. 

@eoli3n I'd rather keep the UI as simple as possible for the moment.

**Comment by eoli3n** [comment]
"save as" function should be a default workflow for a tool which edit a file

**Comment by apiraino** [comment]
> "save as" function should be a default workflow for a tool which edit a file

hi @eoli3n! I think the use case for this tool (and similar ones) is to take a quick snapshot to share once and then forget about it (example: I have a lot of images in ~/tmp that I purge once in a while).

If one screenshot is "important" and needs a name you can rename it from the cli or a file manager.

If you need to rename a lot of screenshots you are probably on another workflow, you can hack a script together (for example) using `zenity` (if you have GTK+ installed) and instead of clicking the save button, just press esc after editing your screenshot:
```
#!/bin/bash
filename=`zenity --entry`
grim -g "$(slurp)" - | swappy -f - -o $filename
```

hth

**Comment by eoli3n** [comment]
Right, why not, that's actually what I use without snappy : https://github.com/eoli3n/dotfiles/blob/master/roles/sway/templates/config.j2#L117
But I still think that it would not trouble the UI to add a "saveas" feature. And it may be benefit a lot to the workflow.

> If one screenshot is "important" and needs a name you can rename it from the cli or a file manager.

That's what i'm trying to avoid. If you want to, for exemple, create a documentation with screenshot, swappy is the right tool, you can draw some instructions on screenshot. I would be able to create a dir ``tool-doc`` and save files in it as ``tool-doc/tool1.png``, ``tool-doc/tool2.png``, etc.

![screen](https://user-images.githubusercontent.com/14223657/107855245-7290cb00-6e21-11eb-914c-f2f67580f996.png)

You see the problem ?

Using cli or file manager is heavier, and swappy could handle this easily without the UI becoming less clean. You could save an odt with libreoffice and then use cli or file manager to rename it, same for every tools that create some files. But tools provides save as feature.

Two ways:
![Swappshot Sat Feb 13 17:26:23 2021](https://user-images.githubusercontent.com/14223657/107855091-b8995f00-6e20-11eb-8950-ad6afa21f777.png)

Or create a "select dir" and "set filename" in edit menu.

**Comment by eoli3n** [comment]
In any cases, the tool is great, thanks for it. Just want it to go a little more further :rocket:
