### ISSUE TITLE
Save error when using the same strftime variable twice

### ISSUE THREAD

**Issue by jinks** [jtheoof/swappy#74]
I was experimenting with the save_file_fmt config and it appears re-using the same placeholder twice makes the save fail.

config parameter:
`save_filename_format=%Y-%m-swappy-%Y%m%d-%H%M%S.png`

Result:
`** (swappy:1600448): CRITICAL **: 04:36:19.122: unable to save drawing area to pixbuf: Failed to open “/home/jinks/Pictures/Screenshots/2021-01-swappy-20210120-043619.p��e	�\u007f” for writing: Invalid or incomplete multibyte or wide character`

**Comment by jtheoof** [comment]
@jinks I can't reproduce this issue even with the same `save_filename_format` as you. How are you running swappy?

**Comment by jtheoof** [comment]
@jinks I could reproduce and fix it.
