### ISSUE TITLE
save_filename_format is not part of the release or help and does not seem to work

### ISSUE THREAD

**Issue by d4g** [jtheoof/swappy#76]
See description.

Config:
```
cat .config/swappy/config                                                      ~
[Default]
save_dir=$HOME/screenshots
save_filename_format=%Y-%m-%d-%H:%M:%S.png
show_panel=true
line_size=5
text_size=20
text_font=sans-serif
```

When I click on save in swappy, it creates a file named like this instead:
```
'Swappshot Mon Jan 25 14:18:05 2021.png'
```

**Comment by jtheoof** [comment]
What version of swappy are you using?

**Comment by d4g** [comment]
swappy version 1.2.1

**Comment by jtheoof** [comment]
You need to use the git build of swappy for now (`swappy-git` on Arch). I haven't released an official version with those changes. Hopefully in a soon to come release.
