### ISSUE TITLE
[Feature request] echo output file path on stdout

### ISSUE THREAD

**Issue by eoli3n** [jtheoof/swappy#77]
I used to 
```
grimshot save area /home/user/img/grimshots/$(zenity --entry --text "Set filename:" --entry-text ".png") | wl-copy -p
```
and want to replace by 
```
grimshot save area - | swappy -f -
```

My first problem is https://github.com/jtheoof/swappy/issues/61#issuecomment-776624045
Second is that swappy doesn't echo the output filename to let me autocopy this with ``| wl-copy -p``

Then a question : why swappy doesn't exit when saving the file ?
I would, when finish editing and set filename in editor panel, save to "exit swappy and print file path on stdout"

**Comment by jtheoof** [comment]
If you simply want to pipe the output of your final swappy buffer to `wl-copy` you can simply use the `-o` option. See the manual page.

Ex:

```
grim -g "$(slurp)" - | swappy -f - -o - | wl-copy
```

**Comment by eoli3n** [comment]
That's not what i want, i don't want to copy the image, i want to copy its path

**Comment by eoli3n** [comment]
> Then a question : why swappy doesn't exit when saving the file ?
> I would, when finish editing and set filename in editor panel, save to "exit swappy and print file path on stdout"

**Comment by UltraBlackLinux** [comment]
I actually want to do the exact same right now. Please implement this.

**Comment by eoli3n** [comment]
Up

**Comment by eoli3n** [comment]
please reopen
