### ISSUE TITLE
cairo status: out of memory

### ISSUE THREAD

**Issue by objectivephoenix** [jtheoof/swappy#79]
I'm getting the following error when trying to use swappy.

```
** (swappy:103534): WARNING **: 13:22:12.535: error while loading png file: /data/downloads/avatar.jpg - cairo status: out of memory
```

I used the following commands

```
$ swappy -f /data/downloads/avatar.jpg
$ grimshot | swappy -f -
```

Both of them produce the same error message.

Some information which might be helpful.

OS - Arch Linux 5.10.13
Swappy Version - 1.2.1
Terminal - Kitty, QTerminal
Shells - Bash, Fish
Display Server - Wayland
Window Manager - sway version 1.5.1

**Comment by ammgws** [comment]
You need to give it a PNG not JPG

**Comment by objectivephoenix** [comment]
So JPG aren't supported yet? Are there plans to support JPG? What about other formats like WEBP?

**Comment by jtheoof** [comment]
Hi @objectivephoenix only PNG are supported at this time. I recommend to use a converter and give the output to swappy. If you are having similar issues with PNG files, please let me know.
