### ISSUE TITLE
No longer prints to stdout

### ISSUE THREAD

**Issue by Biont** [jtheoof/swappy#8]
The command chain `grim -g "$(slurp)" - | swappy -f - -o - ` no longer produces any output for me.
I believe this started today, so maybe something in 320dae02d0c6dca3fa2fd7ca934a85483ac2dd35 broke it?

Saving pictures regularly seems to be unaffected

**Comment by jtheoof** [comment]
OK I'll revert @pathetic-lynx patch until I understand a little bit more the issue.

**Comment by jtheoof** [comment]
@Biont quick question for you, how do you exit swappy? Do you use the `Escape` or `q` key? Temporary fix after the commit you mentioned would be to use a Compositor window killer until I have a better fix. Example in sway `$mod+q` (by default). Let me know if that helps.

**Comment by pathetic-lynx** [comment]
Cannot reproduce, output to stdout when killing swappy using sway does not work in either 196f7f4 or 320dae0, killing with `q` works in both.

@Biont can you investigate more?

**Comment by Biont** [comment]
So I usually `Escape` out of swappy, but hitting `q` does not seem to make a difference.
