### ISSUE TITLE
Icons are not taken from font-awesome

### ISSUE THREAD

**Issue by Algram** [jtheoof/swappy#91]
Hi there,

on my nixos system with sway, I do get ugly fall back icons when using swappy:
![image](https://user-images.githubusercontent.com/5053729/108595510-850a8780-7380-11eb-9e7e-4e89d92a7e4c.png)

font-awesome is installed though.

Sidenote: Why do you even rely on fontawesome? I don't know exactly how e.g. nautilus does not, but they also can provide good looking icons without fontawesome.

Thanks!

**Comment by jtheoof** [comment]
The images in the header bar are taken from your GTK icon theme. Those are not linked to Font Awesome. `edit-undo` `edit-redo`, ... You can customize those in Gnome Tweaks for example.

Can you provide a screenshot of your open side panel ?

**Comment by Algram** [comment]
@jtheoof Sure, it looks like that:
![image](https://user-images.githubusercontent.com/5053729/108624611-3d4e3380-7446-11eb-9818-9dfd5ed1e2b7.png)

Maybe it is also a combination with nixos and something is missing from the `swappy` build here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/swappy/default.nix

I am not sure though.

**Comment by jtheoof** [comment]
So the brush, text, ... icons are taken from FA properly. I think your issue is not related to swappy. If you open `gedit` for example, I think you'll see the exact same icons you are showing. You need to configure your GTK theme properly withing your environment.

**Comment by Algram** [comment]
@jtheoof I finally figured out on how to configure the GTK theme for swappy. I have a follow up question: I am using the `Papirus` icon theme now and it seems to not work with swappy correctly:

![image](https://user-images.githubusercontent.com/5053729/132955364-be451cf4-7539-40eb-9928-019dcee480d7.png)

The icons seem pretty dim. In a different application, e.g. nautilus it looks fine:
![image](https://user-images.githubusercontent.com/5053729/132955380-5365c67f-a6ca-411d-8e03-8e29bffa66f6.png)
